base_url = "https://leoriether.github.io"
theme = "zerm"
taxonomies = [
    {name="categories", feed=true},
    {name="tags", feed=true},
]

compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true
feed_filename = "atom.xml"


[markdown]
highlight_code = true
highlight_theme = "ayu-dark"


[extra]
author = "Leonardo Alves Riether"
logo_text = "WIP"
theme_color = "blue"

main_menu = [
    {url="/posts", name="posts"},
    {url="/categories", name="categories"},
    {url="/tags", name="tags"},
    {url="/snippets", name="snippets"},
    {url="/about", name="about me"},
]

show_author = true
show_categories = true
show_tags = true

center = true

custom_css = true

